# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

threshold_adaptive <- function(mat, k, windowsize, maxsd) {
    .Call(`_pliman_threshold_adaptive`, mat, k, windowsize, maxsd)
}

sobel_help <- function(A) {
    .Call(`_pliman_sobel_help`, A)
}

rgb_to_hsb_help <- function(r, g, b) {
    .Call(`_pliman_rgb_to_hsb_help`, r, g, b)
}

rgb_to_srgb_help <- function(rgb) {
    .Call(`_pliman_rgb_to_srgb_help`, rgb)
}

help_edge_thinning <- function(img) {
    .Call(`_pliman_help_edge_thinning`, img)
}

help_dist_transform <- function(bin) {
    .Call(`_pliman_help_dist_transform`, bin)
}

help_watershed <- function(binary, labels, distances) {
    .Call(`_pliman_help_watershed`, binary, labels, distances)
}

help_get_rgb <- function(R, G, B, labels) {
    .Call(`_pliman_help_get_rgb`, R, G, B, labels)
}

help_get_renir <- function(RE, NIR, labels) {
    .Call(`_pliman_help_get_renir`, RE, NIR, labels)
}

bounding_box <- function(img, edge) {
    .Call(`_pliman_bounding_box`, img, edge)
}

isolate_objects5 <- function(img, labels) {
    .Call(`_pliman_isolate_objects5`, img, labels)
}

help_isolate_object <- function(R, G, B, labels, remove_bg, edge) {
    .Call(`_pliman_help_isolate_object`, R, G, B, labels, remove_bg, edge)
}

help_shp <- function(rows, cols, dims, buffer_x, buffer_y) {
    .Call(`_pliman_help_shp`, rows, cols, dims, buffer_x, buffer_y)
}

help_otsu <- function(img) {
    .Call(`_pliman_help_otsu`, img)
}

helper_guo_hall <- function(image) {
    .Call(`_pliman_helper_guo_hall`, image)
}

idw_interpolation_cpp <- function(x, y, values, new_x, new_y, power = 2) {
    .Call(`_pliman_idw_interpolation_cpp`, x, y, values, new_x, new_y, power)
}

add_width_height_cpp <- function(grid, width, height, points_align) {
    .Call(`_pliman_add_width_height_cpp`, grid, width, height, points_align)
}

help_area <- function(coord) {
    .Call(`_pliman_help_area`, coord)
}

help_slide <- function(coord, fp = 1L) {
    .Call(`_pliman_help_slide`, coord, fp)
}

help_distpts <- function(data) {
    .Call(`_pliman_help_distpts`, data)
}

help_centdist <- function(data) {
    .Call(`_pliman_help_centdist`, data)
}

help_rotate <- function(polygon, angle) {
    .Call(`_pliman_help_rotate`, polygon, angle)
}

help_align <- function(coord) {
    .Call(`_pliman_help_align`, coord)
}

help_lw <- function(coord) {
    .Call(`_pliman_help_lw`, coord)
}

help_eigen_ratio <- function(coord) {
    .Call(`_pliman_help_eigen_ratio`, coord)
}

help_calliper <- function(coord) {
    .Call(`_pliman_help_calliper`, coord)
}

help_elongation <- function(coord) {
    .Call(`_pliman_help_elongation`, coord)
}

help_flip_y <- function(shape) {
    .Call(`_pliman_help_flip_y`, shape)
}

help_flip_x <- function(shape) {
    .Call(`_pliman_help_flip_x`, shape)
}

help_mc <- function(coords) {
    .Call(`_pliman_help_mc`, coords)
}

help_limits <- function(mat) {
    .Call(`_pliman_help_limits`, mat)
}

help_moments <- function(data) {
    .Call(`_pliman_help_moments`, data)
}

get_area_mask <- function(mask) {
    .Call(`_pliman_get_area_mask`, mask)
}

polygon_to_binary <- function(polygon) {
    .Call(`_pliman_polygon_to_binary`, polygon)
}

sum_true_cols <- function(x) {
    .Call(`_pliman_sum_true_cols`, x)
}

help_poly_angles <- function(coords) {
    .Call(`_pliman_help_poly_angles`, coords)
}

help_smoth <- function(coords, niter) {
    .Call(`_pliman_help_smoth`, coords, niter)
}

